name: Frontend CI

on:
  push:
    branches:
      - main # Run on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allow read access to repository contents
      packages: write # Allow writing to GitHub Packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build Next.js standalone app
        run: |
          npm run build
          # Copy public and static assets to standalone folder
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static

      - name: Verify standalone app starts
        run: |
          node .next/standalone/server.js &
          sleep 10
          # Optionally, add curl or other checks here to verify the app responds

      - name: Configure npm for GitHub Packages
        run: |
          echo "@tvaneynde:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: delete old package versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X DELETE \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/users/tvaneynde/packages/npm/se-frontend"

      - name: Prepare package for publishing
        run: |
          cp -r .next/standalone ./standalone

      - name: Copy startup script into standalone folder
        run: |
          # Make sure startup.sh is executable locally
          chmod +x startup.sh

          # Copy it into the same folder you publish (so it ends up in /standalone)
          cp start.sh .next/standalone/startup.sh

      - name: Publish package to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
